apiVersion: app.fybrik.io/v1alpha1
kind: FybrikApplication
metadata:
  name: hello-world-module-test
spec:
  selector:
   workloadSelector:
     matchLabels: {}
  appInfo:
    intent: fraud-detection
  data:
    - dataSetID: "fybrik-notebook-sample/paysim-csv"
      requirements: 
        copy:
          catalog: {}
          required: true
        interface:
          dataformat: csv
          protocol: s3
