---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "hw-module.fullname" . }}
spec:
  template:
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "hw-module.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.imagePullPolicy }}
        name: {{ template "hw-module.fullname" . }}
        env:
        {{- range concat (.Values.global.environment) (.Values.environment | default list)}}
        - name: {{ .name | quote}}
          value: {{ .value | quote }}
        {{- end }}
        {{- if .Values.command }}
        command: {{ .Values.command }}
        {{- end }}
        {{- if .Values.args }}
        args: {{ .Values.args }}
        {{- end }}
        {{- with .Values.resources }}
        resources:
{{ toYaml . | indent 10 }}
        {{- end }}
        volumeMounts:
        - name: "{{ template "hw-module.fullname" . }}-config"
          mountPath: "/etc/config"
          readOnly: true
      volumes:
      - name: {{ template "hw-module.fullname" . }}-config
        configMap:
          name: {{ template "hw-module.fullname" . }}-config
      {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
      {{- end }}
      restartPolicy: {{ .Values.restartPolicy }}
  backoffLimit: {{ .Values.backoffLimit }}